### ISSUE TITLE
Please implement your own keys in your build

### ISSUE THREAD

**Issue by umbrellaplug** [kodi7rd/kodi7rd.github.io#1]
Your build is driving a large amount of traffic to a particular addon. (You know which one) :)
Can you please implement your own trakt, tmdb, and fanart keys? 
Can you please host your own package of coco-scrapers instead of pointing to the coco-joe repo?
Also can you change the logo and name of the addon?

It's okay to continue using it and myself and "another" developer can assist you in forking the add-on, making these changes, and hosting things yourself. We do not want to get red flagged from the extra traffic and attention and it's almost doubled recently. I'm trying to reach out to you before changes are made to prevent the keys from getting too much traffic.

**Comment by TwilightMercy** [comment]
Of course, please read my message to the particular addon developer here:

https://github.com/Tikipeter/repository.tikipeter/issues/245#issuecomment-1605489874
