### ISSUE TITLE
Advanced Search Checkbox 'WithSubsOnly' Not Returning Correct Results on Ktuvit

### ISSUE THREAD

**Issue by Nitzantomer1998** [kodi7rd/kodi7rd.github.io#2]
Hi,

I'm currently developing an addon for Stremio that utilizes Ktuvit and wanted to share some insights based on my experience with your project which been a guideline to mine.

Firstly, thank you for your work on the Ktuvit API. As you likely know, Ktuvit's architecture and structure are quite problematic, requiring scanning over an HTML page, not utilizing imdbID and such.

I've discovered an issue with the advanced search function. If you check the "WithSubsOnly" checkbox, it unfortunately doesn't filter good enough, it may block you result that tag as no subtitles when they actually has due to poor design.

For example, try searching for the TV series "The Gentlemen" (tt13210838) in the advanced search. If you check the "WithSubsOnly" checkbox, it won't show up. However, if you leave the checkbox unchecked, the series will appear and you will find subtitles available within the results.

https://github.com/kodi7rd/kodi7rd.github.io/blob/de902b5362d370a58d6fdce404270a831269164b/builds/build21_kodirdil/build21_kodirdil/addons/service.subtitles.All_Subs/resources/sources/ktuvit.py#L178

Note: I saw you set it to True only if its a movie, i didn't encounter yet a case of movie that act like it but its most likely from the same reasons will be the same.

**Comment by TwilightMercy** [comment]
This is indeed poor Ktuvit design - in advanced search, WithSubsOnly=True will never work for TV Shows, any TV Show:
![image](https://github.com/kodi7rd/kodi7rd.github.io/assets/29895680/7adb3fd5-5433-46d5-b78d-928d1bde8faa)

Therefore it has to always be False for TV Shows. 

For Movies:
WithSubOnly=True does work properly and filter out movies with 0 subtitles uploaded. 

When you search for a movie in advanced search - Ktuvit always limits the results to 20 in the results page. 

If you’ll search for the movie “Barbie” (2024) with WithSubsOnly=False,
You’ll get 20 results of old Barbie movies, and 2024 won’t be there.  

But with WithSubsOnly=True - it filters out movies with no subtitles, and Barbie 2024 appears in the results. 

![image](https://github.com/kodi7rd/kodi7rd.github.io/assets/29895680/038820ab-6591-4c4f-ac38-a6bceac1ce0f)

**Comment by TwilightMercy** [comment]
Now, In your code you provide to search:

https://github.com/Nitzantomer1998/StremioHebSubs/blob/d6b52d099afdbd1054d2e65a712660fe6aa8a7ea/src/helpers/ktuvitHelper.js#L92


* Movie/TV Show Name
* Year

And then take the first result’s ID:
https://github.com/Nitzantomer1998/StremioHebSubs/blob/d6b52d099afdbd1054d2e65a712660fe6aa8a7ea/src/helpers/ktuvitHelper.js#L100

The reason I search without any year parameter at all, is to avoid IMDb/TMDb year mismatch which will bring 0 results to search. 

Example:
IMDb - Talk To Me (2022)
https://m.imdb.com/title/tt10638522/

TMDb - Talk To Me (2023)
https://www.themoviedb.org/movie/1008042-talk-to-me

If the metadata that Kodi/Stremio gets from the addon (try TMDb catalogs addon) -
It will provide year=2023 and will bring 0 results.

**Comment by TwilightMercy** [comment]
Looping through Ktuvit results, and looking for IMDb match between ktuvit result and metadata from Kodi/Stremio:

https://github.com/kodi7rd/kodi7rd.github.io/blob/de902b5362d370a58d6fdce404270a831269164b/builds/build21_kodirdil/build21_kodirdil/addons/service.subtitles.All_Subs/resources/sources/ktuvit.py#L210

**Comment by Nitzantomer1998** [comment]
Oh man, I swear I hate it when things don't work as they should. The mismatch between IMDb and TMDb is a significant flaw.

The functionality of the Ktuvit website is seriously lacking. I wish there was a way to contact the developer and suggest collaborating to rebuild the website from scratch.

Just to note, I'm fetching data about a Movie/TV Series using IMDb, so it matches Ktuvit. Therefore, I don't have that problem.
> Example:
> IMDb - Talk To Me (2022)
> https://m.imdb.com/title/tt10638522/
> 
> TMDb - Talk To Me (2023)
> https://www.themoviedb.org/movie/1008042-talk-to-me


Note: using the library name-to-imdb is sadly not stable and doesnt always work, looked for using TMDb but after knowing this issue i will search for only IMDb.

**Comment by TwilightMercy** [comment]
Self note:

Implement and test @Nitzantomer1998 suggestion, to use metadata IMDb ID to manually parse title + year from website's HTML for search query, and always choose the first result.
